name: Build and merge containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  packages: write
  contents: write
  id-token: write
  attestations: write

jobs:
  build_container:
    name: Build and Push Containers
    strategy:
      fail-fast: false
      matrix:
        model: [louvain]
        os: [blacksmith-2vcpu-ubuntu-2404, blacksmith-2vcpu-ubuntu-2404-arm]
    uses: taranis-ai/github-actions/.github/workflows/build-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-${{ github.event.repository.name }}
      model: ${{ matrix.model }}
      os: ${{ matrix.os }}

  merge_container:
    name: Merge Container Manifests
    needs: build_container
    strategy:
      fail-fast: false
      matrix:
        model: [louvain]
    uses: taranis-ai/github-actions/.github/workflows/merge-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/taranis-${{ github.event.repository.name }}
      model: ${{ matrix.model }}
      latest: ${{ matrix.model == 'louvain' }}
